version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
  test:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm test
  doc:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm -v
workflows:
  version: 2
  build_test_hold_doc:
    jobs:
      - build
      - test
         requires:
         - build
      - hold
        type: approval
        requires:
          - test
      - doc
        requires:
        - hold
        
